FROM centos:8
# FROM centos/python-38-centos7

RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y install python3.8 maven  java-17-openjdk git wget unzip yum-utils && package-cleanup --leaves --all

RUN pip3 install pip==24.2

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

RUN git clone https://github.com/Fedict/best-tools.git

WORKDIR /best-tools/java/

ENV JAVA_HOME="/usr/lib/jvm/jre-17/"

RUN mvn clean install -DskipTests

COPY run.sh prepare_best_files.py convert_xml2csv.sh /