FROM bepelias/base

RUN yum -y install maven java-17-openjdk git wget unzip yum-utils && package-cleanup --leaves --all

RUN git clone https://github.com/Fedict/best-tools.git

WORKDIR /best-tools/java/

ENV JAVA_HOME="/usr/lib/jvm/jre-17/"

RUN mvn clean install -DskipTests

COPY prepare_best_files.py ./scripts/convert_xml2csv.sh ./scripts/prepare_csv.sh /