# This is a basic workflow that is manually triggered

name: Build & feed bePelias

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      region:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Region to build (all, bru, wal or vlg)'
        # Default value if no value is explicitly provided
        default: 'all'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Check out repository code
          uses: actions/checkout@v1.0.0
        - name: Check files
          run: ls
        - name: Run build script for API
          run: ./scripts/build.sh api
        - name: Run build script for Pelias
          run: ./scripts/build.sh pelias
        - name: Get BeSt Address data
          run: ./scripts/feed.sh all  ${{ inputs.region }}
